name: 🚀 Deploy

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build API
        run: |
          pnpm turbo run build --filter=api --scope=apps/api

      - name: Build Web (Nuxt 3)
        run: |
          pnpm turbo run generate --filter=web --scope=apps/web

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/uno-online &&
            pm2 restart uno-api || pm2 start /var/www/uno-online/apps/api/dist/main.js --name uno-api
            npx serve -s /var/www/uno-online/apps/web/.output/public --port 3001 --name uno-web
